name: Terraform Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**' # Trigger on changes in the infra directory
  workflow_dispatch: # Enables manual trigger

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run:  |
        cd infra
        terraform init
      terraform init

    - name: Terraform Lint
      run: terraform fmt -check

    - name: Terraform Plan  
      run: |
      cd infra
      terraform plan

    - name: Terraform Apply
      run: |
      cd infra
      terraform apply -auto-approve
      env:
        TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_region: us-east-1